FROM debian:jessie
MAINTAINER Ben Brunton "ben.b.brunton@gmail.com"

ENV DEBIAN_FRONTEND=noninteractive
ENV RUST_LOG=info

EXPOSE 3000

RUN apt-get update 
RUN apt-get install -y libssl-dev 

COPY project/ /project

WORKDIR /project

EXPOSE 3000

CMD ["/project/target/release/pd_server"]
