version: '3'
services:
  pd_dev:
    tty: true
    image: benbrunton/pusoy_dos
    build: ..
    container_name: pd-dev
    environment:
      RUST_LOG: info
      RUST_BACKTRACE: 1
    volumes:
    - ../project:/project
    stdin_open: true
    ports:
    - 3000:3000

  mysql:
    image: mysql
    container_name: test-mysql
    ports:
      - 6603:3306
    volumes:
    - ../project/mysql:/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "pusoy_dos"

  site-reverse-proxy:
    image: nginx:alpine
    tty: true
    ports:
    - 80:80
    volumes:
    - ../config/nginx.conf:/etc/nginx/nginx.conf

  ws:
    image: socket
    build: ../chat
    container_name: ws-dev
    volumes:
    - ../chat/app:/app

  redis:
    image: redis:3.2.11-alpine
    volumes:
      - ./redis_data:/data
    restart: always


